/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'liurong' at '17-11-16 下午7:44' with Gradle 3.0
 *
 * @author liurong, @date 17-11-16 下午7:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
